apiVersion: v1
kind: Secret
metadata:
  name: llm-s3-secrets
  namespace: llm
  annotations:
    serving.kserve.io/s3-endpoint: minio.minio.svc:9000
    serving.kserve.io/s3-usehttps: "0"
    serving.kserve.io/s3-region: us-east-1
    serving.kserve.io/s3-useanoncredential: "false"
type: Opaque
stringData:
  AWS_ACCESS_KEY_ID: zlt7AuLCUd6cfYSqukH1
  AWS_SECRET_ACCESS_KEY: HnbOq9XKYAfTEXvFIHPk29a1HkMeCQiqFTdwyte6